### ISSUE TITLE
Software/AX3/cwa-convert/java output is not matching with Software/AX3/cwa-convert/c

### ISSUE THREAD

**Issue by vgandikota83** [digitalinteraction/openmovement#46] opened 2021-12-03 06:45 UTC
Hi,

As per the update of [issue 45](https://github.com/digitalinteraction/openmovement/issues/45), i downloaded the latest code and tried to convert the CWA file.

Below are the observations.

The Java output is not matching with C output. Output values are completely different. 
C output contains 2244360 records and java output contains 224320 records
Java output contains duplicate timestamps but C output doesn't have any duplicates

**Comment by danielgjackson** [comment] 2021-12-20 03:03
This is a duplicate of Issue 45, and that issue already covers these points:

* The caveats discussed mention that one sector does appear to be missing in the Java output (this will be 40 samples in AX6 data).
* The caveats also state that the full time precision is not used.  The duplicate timestamps should only appear in the first sector, and this is because each sector only contains a single timestamp and the Java code relies on interpolating between them, yet only processes one sector at a time.  

The one or two affected sectors represent a tiny fraction of any file, and will not materially affect any epoch-based calculations.

I am closing this issue as it is a duplicate, and the Java code is not actively maintained, and the underlying mechanism used is not going to change in the near future.  (But pull requests fixing this are welcome)

**Closed by danielgjackson** 2021-12-20 03:03 UTC
